### PR TITLE
[Rebuild] Dspace 7 Upgrade Sprint II

### LINKED ISSUE #3: Reimplement Capstones theme
https://oaktrust.library.tamu.edu/handle/1969.1/94972
https://oaktrust.library.tamu.edu/handle/1969.1/94973

https://github.com/TAMULib/DSpace/blob/tamu-dspace-6.3/dspace/config/xmlui.xconf#L187

https://github.com/TAMULib/DSpace/tree/tamu-dspace-6.3/dspace/modules/xmlui/src/main/webapp/themes/Mirage2Ext/Capstones

### LINKED ISSUE #23: Minor style regression in TAMU theme header
Image

### PR DESCRIPTION
**Pull request by qtamu**
Resolves #3
Resolves #23

### CODE REVIEW

**Review by rhundal7 — APPROVED** [review]

File: src/app/item-page/mirador-viewer/mirador-viewer.component.ts [hunk 1]
```diff
@@ -70,7 +70,8 @@ export class MiradorViewerComponent implements OnInit {
     const manifestApiEndpoint = encodeURIComponent(environment.rest.baseUrl + '/iiif/'
       + this.object.id + '/manifest');
     // The Express path to Mirador viewer.
-    let viewerPath = '/iiif/mirador/index.html?manifest=' + manifestApiEndpoint;
+    let viewerPath = `${environment.ui.nameSpace}${environment.ui.nameSpace.length > 1 ? '/' : ''}`
```
Comment (jsavell) [inline src/app/item-page/mirador-viewer/mirador-viewer.component.ts:73]: Should we mark this as a TAMU Customization?

**Review by jsavell — APPROVED** [review]
